---
title: "Applying FAIR4RS to your projects"
author: "Sylvia Whittle"
format:
    revealjs:
        theme: [serif]
        smaller: false
        slide-number: true
        scrollable: false
        embed-resources: true
---

## Our project in March 2022

- On GitHub
- Two developers
- Changes made by one would break the other's code
- Difficult to install (sometimes impossible!)
- Deprecated python 2.7
- To change a variable, you had to open the code

---

## What did we do?


---

## Updating to python 3.X: process

- Started from scratch
- Had to ditch some dependencies
- Updated others
- Wrote our own code to replace some of the dependencies that were no longer compatible

#### Effort: 4 months

---

## Updating to python 3.X: benefits

- Code was more stable
- More people could use it
- Online help was more available

---

## Improving installation: process

- Removed the need to install dependencies separately by writing our own code to replace them
- Turned the project into a python 3.X package
- Published the code to PyPI so it can be installed by anyone

```{.bash}
pip install topostats
```

#### Effort: 1 day once the code was ready

---

## Improving installation: benefits

- Friendlier installation -> more users
- Onboarding is faster
- Now works on all computers!
- Time is saved with every new user, and member of our research team

---

## Configuration file: process

- Removed all hard-coded parameters from the code
- Created a configuration file in YAML format
- Wrote code to load the configuration file
- Wrote code to check that the configuration file is valid and makes sense

#### Effort: 1 week for basic functionality

---

## Configuration file: benefits

- Easy way to group parameters into one place
- Users don't have to open the code
- Configurations saved with the output files for reproducibility


---

## Documentation: process

- Wrote a README file to explain the project
- Wrote documentation in the form of docstrings for every function, class and file
- Wrote a tutorial to help users get started
- Set up automatic documentation generation and hosting using Sphinx (involved, but worth it!)

#### Effort: 1 week

---

## Documentation: benefits

- Each function, class and file is explained for developers and users
- Documentation available online as a website
- Automatically generated & updated (no effort once set up!)
- Eliminates the time I spend wondering what a function I wrote 6 months ago does!

[documentation_website](./documentation_website.png)

---

## Code linting: process

- Installed an automatic formatter (black for python)
- Ran the formatter on the code, which automatically re-structures the code to match best practices

#### Effort: 1 hour

- Installed a linter (flake8 for python)
- Ran the linter on the code, which checks that the code is written in a way that adheres to best practices
- Fix the many errors and warnings

### Effort: 1 month

---

## Code linting: benefits

- Everyone speaks the same coding "dialect"
- Code is easier to read and understand
- Bugs are harder to introduce when following best practices
- Reinforces good coding habits

---

## Versioning: process

- Set up versioning on GitHub
- Set up automatic versioning on PyPI
- Set up automatic documentation versioning & generation using Sphinx

#### Effort: 1 day for basic functionality

---

## Versioning: benefits

- Development versions are on GitHub
- Stable versions are released to PyPI
- Documentation is versioned too!

---

## Testing: process

- Wrote tests for every function, class and file
- Set up automatic testing on GitHub using GitHub Actions


#### Effort: Months, ongoing

---

## Testing: benefits

- Difficult to begin with
- Adds time to development
- More than makes up for it when writing new features

---

## Our project in 2023

- 250 ish downloads per month on PyPI
- Collaborators around the world
- 70% test coverage
- 95% ish documentation coverage

---

# Reassurances

- You don't have to do it all at once
- You don't have to do it all yourself
- You don't have to do it perfectly
- Every little helps

---